### ISSUE TITLE
is_assur_bemelacha() seems to work incorrectly - may be because I pass a timezone

### ISSUE THREAD

**Issue by CompuGeniusCode** [pinnymz/python-zmanim#20]
```python
async def shabbos_or_yom_tov():
    now = datetime.now(pytz.timezone("America/New_York"))
    issur_now = calendar.is_assur_bemelacha(now)
    issur_soon = calendar.is_assur_bemelacha(now + timedelta(minutes=60))
    issur_earlier = calendar.is_assur_bemelacha(now - timedelta(minutes=60)

    condition = issur_now or issur_soon or issur_earlier
    logging.info(f"Currently Shabbos/Yom Tov: {condition}")
    return condition
```

This code returned true for Thursday night and returned False this entire Shabbos, although did return False on Friday night.
`Thu Jul 18 - 11:13:34 PM | INFO | Currently Shabbos/Yom Tov: True`
`Fri Jul 19 - 08:17:41 PM | INFO | Currently Shabbos/Yom Tov: True`
`Sat Jul 20 - 08:47:57 AM | INFO | Currently Shabbos/Yom Tov: False`

**Comment by pinnymz** [comment]
You aren't specifying how `calendar` (which is implied to be a `ZmanimCalendar` object) was instantiated, or how often it is refreshed.  Calling `is_assur_bemelacha` will not change the internal date, so you'll need to do that yourself first by calling:
`calendar.date = now.date`

Clearly, this method contains a footgun since it isn't obvious that the internal date and the passed date need to match. It may make sense to address this in an upcoming release...

**Comment by CompuGeniusCode** [comment]
> You aren't specifying how `calendar` (which is implied to be a `ZmanimCalendar` object) was instantiated, or how often it is refreshed. Calling `is_assur_bemelacha` will not change the internal date, so you'll need to do that yourself first by calling: `calendar.date = now.date`
> 
> Clearly, this method contains a footgun since it isn't obvious that the internal date and the passed date need to match. It may make sense to address this in an upcoming release...

Didn't realize that you responded and came to write the solution you suggested. Thanks for your help!
